version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: app
    restart: always
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/postgres"
    ports:
      - "8080:8080"
    volumes:
      - ./app:/app
    depends_on:
      - postgres

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - app

  postgres:
    image: postgres:11
    container_name: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
